---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: block-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath: 
    path: /tmp/data_app
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 200Mi
  storageClassName: manual

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: adddeploy
spec: 
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels: 
      app: kubeapp
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: kubeapp
      name: kubepods
    spec: 
      containers: 
        - 
          image: "timjar3/pubrepo1:58"
          name: kubeapp
          ports: 
            - 
              containerPort: 8080
          resources: 
            limits: 
              cpu: 10m
          volumeMounts: 
            - 
              mountPath: /data
              name: my-volume
      volumes: 
        - 
          name: my-volume
          persistentVolumeClaim: 
            claimName: pvc
--- 
apiVersion: v1
kind: Service
metadata: 
  name: addsvc
spec: 
  type: LoadBalancer
  selector: 
    app: kubeapp
  ports: 
    - 
      port: 8080
      targetPort: 8080
  
--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: kubeapphpa
spec: 
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: adddeploy
  targetCPUUtilizationPercentage: 10
