---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: block-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath: 
    path: /tmp/data_app
  storageClassName: manual